In [ ]:
#business problems 
#identify the underperforming brands tht requires promotional or pricing adjustment 
#determine the top vendor contributing to sales and gross profit 
#analyse the impact of bulk purchasing on unit cost assess inventory turnover to reduce holding cost and improve efficiency 
#investigate the profitablity varience betrween high performing and low performing vendors


import pandas as pd
import os
import logging
import time
from sqlalchemy import create_engine

engine = create_engine('sqlite:///inventory.db')

print([f for f in os.listdir() if f.endswith('.csv')])

In [24]:
os.makedirs("logs", exist_ok=True)

logging.basicConfig(
    filename=os.path.join("logs", "project.log"),
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    force=True
)

logging.info("Supply chain project started")
print("Logging setup complete!")

Logging setup complete!

In [25]:
def ingest_db(df, table_name, engine):
    df.to_sql(
        table_name,
        con=engine,
        if_exists='replace',
        index=False
    )

In [26]:

def load_raw_data():
    for file in os.listdir():
        if file.lower().endswith('.csv'):
            try:
                df = pd.read_csv(file)

                logging.info(
                    f"Loaded {file} with shape {df.shape}"
                )

                ingest_db(df, file[:-4], engine)

                logging.info(f"Inserted {file} into database")
                print("Loaded and inserted:", file, df.shape)

            except Exception:
                logging.exception(f"Failed to process {file}")
                print("Error processing:", file)

In [30]:
import time

In [31]:
start_time = time.time()

load_raw_data()

end_time = time.time()

total_time = (end_time - start_time) / 60

print(f"Total loading time: {total_time:.2f} minutes")

Loaded and inserted: end_inventory.csv (224489, 9)
Loaded and inserted: inventory_begin.csv (206529, 9)
Loaded and inserted: purchase.csv (1048575, 16)
Loaded and inserted: purchase_price.csv (12261, 9)
Loaded and inserted: sales.csv (1048575, 14)
Loaded and inserted: vendor_invoice.csv (5543, 10)
Total loading time: 0.51 minutes

In [32]:

import time

start_time = time.time()

load_raw_data()

end_time = time.time()

elapsed = end_time - start_time

print(f"Total time taken: {elapsed:.2f} seconds")
print(f"Total time taken: {elapsed / 60:.2f} minutes")

Loaded and inserted: end_inventory.csv (224489, 9)
Loaded and inserted: inventory_begin.csv (206529, 9)
Loaded and inserted: purchase.csv (1048575, 16)
Loaded and inserted: purchase_price.csv (12261, 9)
Loaded and inserted: sales.csv (1048575, 14)
Loaded and inserted: vendor_invoice.csv (5543, 10)
Total time taken: 30.34 seconds
Total time taken: 0.51 minutes

In [33]:
print(os.path.abspath("inventory.db"))

C:\Users\Medion\inventory.db

In [35]:
import os

print("Current folder:", os.getcwd())
print("Database path:", os.path.abspath("inventory.db"))
print("Database exists:", os.path.exists("inventory.db"))
print("Database size:", os.path.getsize("inventory.db"), "bytes")

Current folder: C:\Users\Medion
Database path: C:\Users\Medion\inventory.db
Database exists: True
Database size: 0 bytes

In [36]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(os.path.abspath("inventory.db"))

tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

display(tables)

Empty DataFrame
Columns: [name]
Index: []

In [37]:
import os

for file in os.listdir():
    if file.lower().endswith(".csv"):
        print(file, os.path.getsize(file), "bytes")

end_inventory.csv 19208497 bytes
inventory_begin.csv 17654249 bytes
purchase.csv 160335321 bytes
purchase_price.csv 1059705 bytes
sales.csv 131302929 bytes
vendor_invoice.csv 515471 bytes

In [38]:
print(engine.url)

sqlite:/// inventory.db

In [39]:
print(os.path.abspath("inventory.db"))

C:\Users\Medion\inventory.db

In [40]:
from sqlalchemy import create_engine

engine = create_engine("sqlite:///inventory.db")
print(engine.url)

sqlite:///inventory.db

In [41]:
with engine.connect() as conn:
    tables = pd.read_sql_query(
        "SELECT name FROM sqlite_master WHERE type='table';",
        conn
    )

display(tables)

Empty DataFrame
Columns: [name]
Index: []

In [42]:
start_time = time.time()

load_raw_data()

end_time = time.time()

print(f"Loading time: {(end_time - start_time) / 60:.2f} minutes")

Loaded and inserted: end_inventory.csv (224489, 9)
Loaded and inserted: inventory_begin.csv (206529, 9)
Loaded and inserted: purchase.csv (1048575, 16)
Loaded and inserted: purchase_price.csv (12261, 9)
Loaded and inserted: sales.csv (1048575, 14)
Loaded and inserted: vendor_invoice.csv (5543, 10)
Loading time: 0.50 minutes

In [43]:
import os

print("File size in MB:", round(os.path.getsize("purchase.csv") / (1024 * 1024), 2))

File size in MB: 152.91